### ISSUE TITLE
Not able to retrieve the original content of the file data/result(758)_label.csv

### ISSUE THREAD

**Issue by amulyalakku** [lixiaojieff/HGTAN#1]
<img width="571" alt="Screen Shot 2021-10-27 at 2 46 53 PM" src="https://user-images.githubusercontent.com/17248698/139136393-66ee04c5-281a-4838-9883-a55c44c15d44.png">

As I cannot refer to the original content of the file _result(758)_label.csv_ I see the below compilation issue. 

<img width="1267" alt="Screen Shot 2021-10-27 at 2 50 17 PM" src="https://user-images.githubusercontent.com/17248698/139136803-e8788bcd-322b-4d5e-bf2f-3fafd8f9109b.png">

**Comment by lixiaojieff** [comment]
Sorry, you can download this 'result(758)_label.csv' file from the Google Drive link: https://drive.google.com/file/d/1T7OHfe8lOrv_fED545yArLDVj8sLVqP2/view?usp=sharing.

**Comment by amulyalakku** [comment]
Thank you, Li, for the quick fix. Appreciate it.
